### ISSUE TITLE
newest WindowsNoEditor0_P.pak fails to decrypt (latest MVCI as of post)

### ISSUE THREAD

**Issue by Labreezy** [AltimorTASDK/dfpslayer#1]
"Not a supported DFP encrypted file
DFP Decryption Mode L not supported" was my error message.

Thank you for all that you do, please support this mode if it is a mode thing and see what's up if it's not...

--Labreezy

**Comment by AltimorTASDK** [comment]
It decrypted fine for me, so I'm not sure what the problem is.

**Comment by Labreezy** [comment]
nvm, files were already decrypted, false alarm.
